# Generated by Django 4.2.4 on 2023-09-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='number_and_name_of_problem',
        ),
        migrations.AddField(
            model_name='problem',
            name='name_of_problem',
            field=models.CharField(default='', max_length=255, verbose_name='название задачи'),
        ),
        migrations.AddField(
            model_name='problem',
            name='number_of_problem',
            field=models.CharField(default='', max_length=255, verbose_name='номер задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='number_of_solution',
            field=models.CharField(default='', max_length=255, verbose_name='количество решений'),
        ),
    ]
