# Generated by Django 4.2.4 on 2023-09-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_number_and_name_of_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name_of_problem',
            field=models.CharField(max_length=255, verbose_name='название задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='number_of_problem',
            field=models.CharField(max_length=255, verbose_name='номер задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='number_of_solution',
            field=models.IntegerField(verbose_name='количество решений'),
        ),
    ]
